adm/urls.py
from django.conf.urls import patterns, include, url
from adm import views
from django.contrib import admin
from views import CadastrarProduto, CategoriaView, SubCategoriaView

urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'connectedin.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),
                       url(r'^adm/index$', CadastrarProduto.as_view(), name='adm'),
                       url(r'^adm/base$', views.base, name='baseAdmin'),
                       url(r'^adm/produto', CadastrarProduto.as_view(), name='produtoAdm'),
                       url(r'^adm/subcategoria', SubCategoriaView.as_view(), name='subcategoria'),
                       url(r'^adm/categoria', CategoriaView.as_view(), name='categoria'),
                       url(r'^cadastrarProduto/$', CadastrarProduto.as_view(), name='cadastrarProduto'),
                       )

loja/urls.py
from django.conf.urls import patterns, include, url
from loja import views
from django.contrib import admin


urlpatterns = patterns('',
                       # Examples:
                       # url(r'^$', 'connectedin.views.home', name='home'),
                       # url(r'^blog/', include('blog.urls')),


                       url(r'^$', views.index, name='index'),
                       url(r'^produto/$', views.produto, name='produto'),
                       url(r'^pagamento/$', views.pagamento, name='pagamento'),
                       )

lojaVirtual/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'lojaVirtual.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
                       url(r'^', include('adm.urls')),
                       url(r'^', include('loja.urls')),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

adm/models.py
from django.db import models

# Create your models here.

loja/models.py
#!/usr/bin/python
# -*- coding: UTF-8 -*-

from django.db import models
from django.utils.timezone import now

class Produto(models.Model):
    nome = models.CharField(max_length=255, null=False)
    valor = models.CharField(max_length=255, null=False)
    qtd = models.CharField(max_length=255, null=False)
    tecido = models.CharField(max_length=255, default='Não informado')
    tamanho = models.CharField(max_length=255, default='Não informado')
    fabricante = models.CharField(max_length=255, default='Não informado')
    origem = models.CharField(max_length=255, default='Não informado')
    descricao = models.TextField(default="Não informado")
    dataAdicionado = models.DateField(default=now())
    qtdVendido = models.CharField(max_length=255, default=0)

class Categoria(models.Model):
    nome = models.CharField(max_length=255, null=True)
    descricao = models.CharField(max_length=255, null=True)
    produtos = models.ManyToManyField(Produto, related_name="categorias")

class SubCategoria(models.Model):
    nome = models.CharField(max_length=255, null=True)
    categoria = models.ForeignKey(Categoria, related_name='subCategoria')

class Imagem(models.Model):
    img = models.ImageField(upload_to='img/%Y')
    descricao = models.CharField(max_length=255, null=True)
    produto = models.ForeignKey(Produto, related_name='imagens')

adm/forms.py
from django.forms import Form, CharField
from django.forms.forms import NON_FIELD_ERRORS
from django.forms.util import ErrorList


class CadastrarProdutoForm(Form):
    nome = CharField(required=True)
    valor = CharField(required=True)
    qtd = CharField(required=True)
    categoria = CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(CadastrarProdutoForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        return valid
    def adiciona_erro(self, message):
        errors = self._errors.setdefault(NON_FIELD_ERRORS, ErrorList())
        errors.append(message)

class CategoriaForm(Form):
    nome = CharField(required=True)
    descricao = CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(CategoriaForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(NON_FIELD_ERRORS, ErrorList())
        errors.append(message)

class SubCategoriaForm(Form):
    nome = CharField(required=True)
    categoria = CharField(required=True)

    def is_valid(self):
        valid = True
        if not super(SubCategoriaForm, self).is_valid():
            self.adiciona_erro('Por favor, verifique os dados informados')
            valid = False

        return valid

    def adiciona_erro(self, message):
        errors = self._errors.setdefault(NON_FIELD_ERRORS, ErrorList())
        errors.append(message)

adm/views.py
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic.base import View
from loja.models import Produto, Categoria, SubCategoria, Imagem
from datetime import datetime
from forms import CadastrarProdutoForm, CategoriaForm, SubCategoriaForm



def base(request):
    return render(request, 'baseAdm.html')


class CadastrarProduto(View):
    template_nome = 'produtoAdm.html'

    def get(self, request):
        return render(request, self.template_nome, {'categorias': Categoria.objects.all()})

    def post(self, request):
        form = CadastrarProdutoForm(request.POST, request.FILES)
        if form.is_valid():
            dados_form = form.data
            # Cria o o produto
            produto = Produto(nome=dados_form['nome'],
                              valor=dados_form['valor'],
                              qtd=dados_form['qtd'],
                              tecido=dados_form['tecido'],
                              tamanho=dados_form['tamanho'],
                              fabricante=dados_form['fabricante'],
                              origem=dados_form['origem'],
                              descricao=dados_form['descricao'],
                              dataAdicionado=datetime.now(),
                              qtdVendido=0)
            produto.save()
            # salva o produto na categoria
            categoria = Categoria.objects.get(id=dados_form['categoria'])
            categoria.produtos.add(produto)
            categoria.save()
            # Cria a img do produto
            img = Imagem(img=request.FILES['img'],
                         descricao=dados_form["desImg"],
                         produto=produto)
            img.save()
            return redirect('produtoAdm')

        return render(request, self.template_nome, {'form': form, 'categorias': Categoria.objects.all()})


class CategoriaView(View):
    template_nome = 'categoriaAdm.html'

    def get(self, request):
        return render(request, self.template_nome)

    def post(self, request):
        form = CategoriaForm(request.POST)
        if form.is_valid():
            dados_form = form.data

            # Cria a categoria
            categoria = Categoria(nome=dados_form['nome'],
                                  descricao=dados_form['descricao'])
            categoria.save()
            return redirect('categoria')
        return render(request, self.template_nome, {'form': form})


class SubCategoriaView(View):
    template_nome = 'subCategoriaAdm.html'

    def get(self, request):
        return render(request, self.template_nome, {'categorias': Categoria.objects.all()})

    def post(self, request):
        form = SubCategoriaForm(request.POST)
        if form.is_valid():
            dados_form = form.data
            # Cria a Subcategoria
            subCat = SubCategoria(nome=dados_form['nome'],
                                  categoria=Categoria.objects.get(id=dados_form['categoria']))
            subCat.save()

            print(subCat.nome)
            print(subCat.categoria.nome)

            return redirect('subCategoria')
        return render(request, self.template_nome, {'form': form, 'categorias': Categoria.objects.all()})

loja/views.py
from django.shortcuts import render
from models import Produto
from models import Categoria, Produto

# Create your views here.

def index(request):
     return render(request, 'index.html', { 'categorias' : Categoria.objects.all(), 'produtos' : Produto.objects.all()})

def produto(request):
     return render(request, 'produto.html')

def pagamento(request):
     return render(request, 'pagamento.html')

adm/templates/baseAdm.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/site.css" %}" rel="stylesheet">
    <link href="{% static "styles/animate.css" %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "scripts/jquery-1.9.1.js" %}"></script>
    <script type="text/javascript" src="{% static "scripts/bootstrap-min.js" %}"></script>
    <script type="text/javascript" src="{% static "scripts/wow.js" %}"></script>
    <title>Loja virtual</title>
</head>
<body>
    <div class="item">
        <img src="{% static "img/admin_banner.jpg" %}" class="fullscreen" alt="Moda Infantil" />
    </div>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-3">
                <h3 class="text-center">Menu</h3>
                <ul class="list-group">
                    <li class="list-group-item"><a href="/adm/produto">Adicionar Produto</a></li>
                    <li class="list-group-item"><a href="/adm/categoria">Adicionar Categoria</a></li>
                    <li class="list-group-item"><a href="/adm/subcategoria">Adicionar Sub-Categoria</a></li>
                </ul>
            </div><!--Fim Menu-->
            <div class="col-xs-12 col-sm-6">
                {% block body %}
                {% endblock %}
            </div>
        </div>
    </div><!--Fim div Container-->
    <footer class="footer">
        <p>Avenida Paulista n 1</p>
        <p>(11) 2239-1234</p>
    </footer>
</body>
</html>

adm/templates/categoriaAdm.html
{% extends "baseAdm.html" %}
{% load static %}
{% block body %}
            <form class="form-signin" role="form" action="{% url 'categoria' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Nova Categoria</legend>
                    <div class="form-group">
                        <label for="id_nome">Nome Categoria:</label>
                        <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Ex: Roupa, Eletronico, Jogo... ">
                    </div>

                    <div class="form-group">
                        <label for="descricao">Descrição :</label>
                        <textarea class="form-control" id="descricao" name="descricao" rows="3"></textarea>
                    </div>

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                             {{form.non_field_errors}}
                        </div>
                    {% endif %}

                </fieldset>
                <button type="submit" class="btn btn-primary btn-block btn-lg">
                    Cadastrar
                </button>
            </form>
{% endblock %}

adm/templates/produtoAdm.html
{% extends "baseAdm.html" %}
{% load static %}
{% block body %}
            <form class="form-signin" action="{% url 'cadastrarProduto' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset>
                    <legend>Cadastrar Produto</legend>
                    <div class="form-group">
                        <label for="id_nome">Nome produto:</label>
                        <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Nome" />
                    </div>

                    <div class="form-group">
                        <label for="valor">Valor:</label>
                        <input type="text" id="valor" name="valor" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="qtd">Quantidade:</label>
                        <input type="number" id="qtd" name="qtd" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="tecido">Tecido:</label>
                        <input type="text" id="tecido" name="tecido" class="form-control" />
                    </div>

                    <div class="form-group">
                        <label for="tamanho">Tamanho:</label>
                        <input type="text" id="tamanho" name="tamanho" class="form-control"/>
                    </div>

                    <div class="form-group">
                        <label for="fabricante">Fabricante:</label>
                        <input type="text" id="fabricante" name="fabricante" class="form-control"/>
                    </div>

                    <div class="form-group">
                        <label for="origem">Origem:</label>
                        <input type="text" id="origem" name="origem" class="form-control"/>
                    </div>

                    <div class="form-group">
                        <label for="descricao">Descrição:</label>
                        <textarea class="form-control" id="descricao" name="descricao" rows="3"></textarea>
                    </div>

                    <div class="form-group">
                        <label for="descricao">Selecione a categoria:</label>
                        <select name="categoria" class="form-control" required>
                            {% for categoria in categorias %}
                                <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <div class="form-group">
                        <label for="img">Imagem</label>
                        <input type="file" id="img" name="img">
                        <p class="help-block">selecione a imagem do produto.</p>
                    </div>

                    <div class="form-group">
                        <label for="desImg">Descrição da Imagem:</label>
                        <textarea class="form-control" id="desImg" name="desImg" rows="3"></textarea>
                    </div>

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                             {{form.non_field_errors}}
                        </div>
                    {% endif %}

                </fieldset>
                <button type="submit" class="btn btn-primary btn-block btn-lg">
                    Enviar
                </button>
            </form>
{% endblock %}

adm/templates/subcategoriaAdm.html
{% extends "baseAdm.html" %}
{% load static %}
{% block body %}
            <form class="form-signin" action="{% url 'subcategoria' %}" method="post">
                {% csrf_token %}
                <fieldset>
                    <legend>Nova Sub-Categoria</legend>
                    <div class="form-group">
                        <label for="id_nome">Nome Sub-Categoria:</label>
                        <input type="text" id="id_nome" name="nome" class="form-control" placeholder="Ex: Roupas, Eletronicos, Jogos... ">
                    </div>

                    <div class="form-group">
                        <label for="descricao">Selecione a categoria :</label>
                        <select name="categoria" class="form-control">
                            {% for categoria in categorias %}
                                <option value="{{ categoria.id }}">{{ categoria.nome }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                             {{form.non_field_errors}}
                        </div>
                    {% endif %}
                </fieldset>
                <button type="submit" class="btn btn-primary btn-block btn-lg">
                    Cadastrar
                </button>
            </form>

{% endblock %}

loja/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width" />
    <link href="{% static "styles/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "styles/site.css" %}" rel="stylesheet">
    <link href="{% static "styles/animate.css" %}" rel="stylesheet">
    <script type="text/javascript" src="{% static "scripts/jquery-1.9.1.js" %}"></script>
    <script type="text/javascript" src="{% static "scripts/bootstrap-min.js" %}"></script>
    <script type="text/javascript" src="{% static "scripts/wow.js" %}"></script>
    <title>Loja virtual</title>
</head>
<body>
    <header class="row">
        <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-header">
                <a href="#" class="navbar-brand">M&M</a>
                <button type="button" data-target=".navbar-collapse" data-toggle="collapse" class="navbar-toggle">Menu</button>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="navbar-nav nav">
                    <li><a href="#novidades">Novidades</a></li>
                    <li><a href="#maisVendidos">Mais Vendidos</a></li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Camisetas
                            <span class="caret"> </span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">Masculinas</a></li>
                            <li><a href="#">Femininas</a></li>
                            <li><a href="#">Infantil</a></li>
                        </ul>
                    </li>
                </ul>
                <form class="navbar-form navbar-right">
                     <div class="form-group">
                         <label class="sr-only" for="exampleInputEmail3">Busca</label>
                         <input type="text" class="form-control" placeholder="Digite a sua busca" />
                     </div>
                    <button type="submit" class="btn btn-default">Buscar</button>
                </form>
            </div>
        </nav>
    </header>
    <main>
        <!--Inicio Carousel-->
        <div class="row" id="home">
            <div id="carousel" class="carousel slide" data-ride="carousel">
                <div class="carousel-inner" role="listbox">
                    <div class="item active">
                        <img src="{% static "img/banner1.jpg" %}" class="fullscreen" alt="Moda" />
                    </div>
                    <div class="item">
                        <img src="{% static "img/banner2.jpg" %}" class="fullscreen" alt="Moda Infantil" />
                    </div>
                </div>
                <a href="#carousel" class="left carousel-control" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a href="#carousel" class="right carousel-control" data-slide="next">
                     <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        <!--Fim Carousel-->
        </div>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div><!--Fim div Container-->
    </main>
    <footer class="footer">
        <p>Avenida Paulista n 1</p>
        <p>(11) 2239-1234</p>
    </footer>
</body>
    <script>
    new WOW().init();
    </script>
</html>

loja/templates/index.html
{% extends "base.html" %}
{% load static %}
{% block body %}
<div class="row">
    <div class="col-xs-12 col-sm-3">
        <h3 class="text-center">Categorias</h3>
        <ul class="list-group">
            {% for categoria in categorias %}
                <li class="list-group-item"><a href="categoria/{{ categoria.id }}">{{categoria.nome}}</a></li>
             {% endfor %}
        </ul>
    </div><!--Fim Categoria-->
    <!--Inicio Novidades-->
    <div class="col-xs-12 col-sm-9 wow fadeInUp" data-wow-delay="1s">
        <div id="novidades">
            <h3 class="text-center">Novidades</h3>
        </div>

        {% for produto in produtos %}
            <div class="col-md-4 thumbnail text-center"><!-- classe "thumbnail" - Adiciona uma borda-->
                <figure>
                    {% for img in produto.imagens.all %}
                        <img src="{{ img.img.url }}" alt="{{ img.img.descricao }}" />
                    {% endfor %}

                    <div>
                        <h4>{{ produto.nome }}</h4>
                        <p>{{ produto.descricao }}</p>
                    </div>
                </figure>
                <p>R$ {{ produto.valor }}</p>
                <a href="#" class="btn btn-primary">Comprar</a>
            </div>
        {% endfor %}

        <div class="col-md-4 thumbnail text-center"><!-- classe "thumbnail" - Adiciona uma borda-->
            <figure>
                <img src="{% static "img/camisa-azul.png"%}" alt="camisa azul importada" />
                <div>
                    <h4>Camisa Azul Importada</h4>
                    <p>Camisa azul importada com preço acessível e com pano de qualidade</p>
                </div>
            </figure>
            <p>R$ 190,00</p>
            <a href="#" class="btn btn-primary">Comprar</a>
        </div>

        <div class="col-md-4 thumbnail text-center"><!-- classe "thumbnail" - Adiciona uma borda-->
            <figure>
                <img src="{% static "img/camisa-rosa.png"%}" alt="camisa azul importada" />
                <div>
                    <h4>Camisa Rosa Importada</h4>
                    <p>Camisa azul importada com preço acessível e com pano de qualidade</p>
                </div>
            </figure>
            <p>R$ 190,00</p>
            <a href="#" class="btn btn-primary">Comprar</a>
        </div>

    </div><!--Fim Novidades-->

    <!--Inicio Mais Vendidos-->
    <div class="col-xs-12 col-sm-9 col-sm-push-3 wow fadeInUp" data-wow-delay="2s">
        <div id="maisVendidos">
            <h3 class="text-center">Mais Vendidos</h3>
        </div>
        <div class="col-md-4 thumbnail text-center"><!-- classe "thumbnail" - Adiciona uma borda-->
            <figure>
                <img src="{% static "img/camisa-azul.png"%}" alt="camisa azul importada" />
                <div>
                    <h4>Camisa Azul Importada</h4>
                    <p>Camisa azul importada com preço acessível e com pano de qualidade</p>
                </div>
            </figure>
            <p>R$ 190,00</p>
            <a href="#" class="btn btn-primary">Comprar</a>
        </div>

        <div class="col-md-4 thumbnail text-center"><!-- classe "thumbnail" - Adiciona uma borda-->
            <figure>
                <img src="{% static "img/camisa-azul.png"%}" alt="camisa azul importada" />
                <div>
                    <h4>Camisa Azul Importada</h4>
                    <p>Camisa azul importada com preço acessível e com pano de qualidade</p>
                </div>
            </figure>
            <p>R$ 190,00</p>
            <a href="#" class="btn btn-primary">Comprar</a>
        </div>

        <div class="col-md-4 thumbnail text-center wow fadeInUp" data-wow-delay="2s"><!-- classe "thumbnail" - Adiciona uma borda-->
            <figure>
                <img src="{% static "img/camisa-rosa.png"%}" alt="camisa azul importada" />
                <div>
                    <h4>Camisa Rosa Importada</h4>
                    <p>Camisa azul importada com preço acessível e com pano de qualidade</p>
                </div>
            </figure>
            <p>R$ 190,00</p>
            <a href="#" class="btn btn-primary">Comprar</a>
        </div>

    </div><!--Fim Mais Vendidos-->
</div><!--Fim div ROW-->

{% endblock %}

loja/templates/pagamento.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <div class="row">
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-tittle">Sua Compra</h2>
                </div>
                <div class="panel-body text-center">
                    <img src="{% static "img/produto.png" %}" alt="Camiseta azul" class="img-responsive img-thumbnail" />
                    <dl>
                        <dt>Nome</dt>
                        <dd>Camiseta azul</dd>

                        <dt>Cor</dt>
                        <dd>Azul</dd>

                        <dt>Tamanho</dt>
                        <dd>G</dd>

                        <dt>Preço</dt>
                        <dd>R$ 129,00</dd>
                    </dl>
                </div>
            </div>
        </div>

    <div class="col-sm-6  col-sm-push-1">
        <form>
            <fieldset>
                <legend>Informações do usuário</legend>
                <div class="form-group">
                    <label for="nome">Nome completo:</label>
                    <input type="text" id="nome" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="cpf">Cpf:</label>
                    <input type="text" id="cpf" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="email">Email:</label>
                    <div class="input-group">
                        <span class="input-group-addon">@</span>
                        <input type="email" id="email" class="form-control" />
                    </div>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" id="novidades" value="sim" />
                        Quero receber novidades da loja
                    </label>
                </div>
            </fieldset>

            <fieldset>
                <legend>Informações de pagamento</legend>
                <div class="form-group">
                    <label for="bandeira">Bandeira</label>
                    <select class="form-control" id="bandeira">
                        <option value="visa">Visa</option>
                        <option value="mastercard">Mastercard</option>
                        <option value="amex">American Express</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="numero">Número</label>
                    <input type="number" id="numero" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="validade">Validade</label>
                    <input type="month" id="validade" class="form-control" />
                </div>
                <div class="form-group">
                    <label for="cvv">CVV</label>
                    <input type="text" id="cvv" class="form-control" maxlength="3" />
                </div>
            </fieldset>
            <button type="submit" class="btn btn-primary btn-block btn-lg">
                <span class="glyphicon glyphicon-thumbs-up"></span>
                Confirmar pedido
            </button>
        </form>
    </div>
</div>
{% endblock %}

loja/templates/produto.html
{% extends "base.html" %}
{% load static %}
{% block body %}
    <div class="row">
        <div class="col-sm-4">
            <img src="{% static "img/produto.png" %}" alt="Camiseta azul" class="img-responsive img-thumbnail" />
        </div>
        <div class="col-sm-6 col-sm-push-1">
            <div class="text-center">
                <h1>Camiseta azul importada</h1>
                <p>R$ 129,00</p>
                <a href="#" class="btn btn-primary btn-lg">Comprar</a>
            </div>
            <!--Inicio abas-->
            <div class="row">
                <ul class="nav nav-tabs">
                    <li class="nav"><a href="#desc" class="active" data-toggle="tab">Descrição</a></li>
                    <li class="nav"><a href="#informacoes" data-toggle="tab">Informações técnicas</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane  fade in active " id="desc">
                        <div class="panel-body">
                        <p>Camiseta azul feita em algodão com caimento perfeito proporcionando leveza e conforto nos movimentos.</p>
                        <p>Camiseta meia manga com decote arrendondado e importada.</p>
                        </div>
                    </div>
                    <div class="tab-pane fade" id="informacoes">
                        <table class="table table-responsive">
                            <tbody>
                                <tr>
                                    <td>Tecido</td>
                                    <td>Algodão</td>
                                </tr>
                                <tr>
                                    <td>Tamanho</td>
                                    <td>P, M, G, GG</td>
                                </tr>
                                <tr>
                                    <td>Fabricante</td>
                                    <td>Caelum</td>
                                </tr>
                                <tr>
                                    <td>Origem</td>
                                    <td>China</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div><!--Fim abas-->
        </div>
    </div>
{% endblock %}